apiVersion: log.alibabacloud.com/v1alpha1
kind: AliyunLogConfig
metadata:
  name: klinematrix-frontend-stdout
  namespace: kube-system
spec:
  logstore: klinematrix-frontend
  logtailConfig:
    configName: klinematrix-frontend-stdout
    inputType: plugin
    inputDetail:
      plugin:
        inputs:
          - type: service_docker_stdout
            detail:
              IncludeK8sLabel:
                app: frontend
              K8sNamespaceRegex: "^klinematrix-prod$"
              Stdout: true
              Stderr: true
        processors:
          - type: processor_default
            detail:
              KeepSource: true
