apiVersion: v1
kind: ServiceAccount
metadata:
  name: klinematrix-sa
  namespace: klinematrix-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: klinematrix-role
  namespace: klinematrix-prod
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: klinematrix-rolebinding
  namespace: klinematrix-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: klinematrix-role
subjects:
- kind: ServiceAccount
  name: klinematrix-sa
  namespace: klinematrix-prod
